Assuming unrestricted shared filesystem usage.
None
host: Allens MacBook
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                   count
------------------  -------
all                       1
write_gene_records        1
total                     2

Select jobs to execute...
Execute 1 jobs...
[Fri Aug 22 21:28:51 2025]
localrule write_gene_records:
    input: isoformDB/intermediates/K562/transcript_annotation.gtf.gz, isoformDB/intermediates/K562/isoform_quantitation.tsv, isoformDB/references/grch38.gencode.v29/cannonical_genes.gff
    output: isoformDB/intermediates/K562/db.commited
    jobid: 1
    reason: Missing output files: isoformDB/intermediates/K562/db.commited
    wildcards: dataset_id=K562
    priority: 1000
    resources: tmpdir=/var/folders/tk/bdsgytmn5cb0bfqrftv10n8r0000gq/T
Shell command: 
        isoformer-write-records \
            --gene-annotation isoformDB/references/grch38.gencode.v29/cannonical_genes.gff \
            --quantitation isoformDB/intermediates/K562/isoform_quantitation.tsv annot_transcript_id rep2ENCSR983KDL \
            --transcript-annotation isoformDB/intermediates/K562/transcript_annotation.gtf.gz \
            --reference-id grch38.gencode.v29 \
            --dataset-id K562 \
            --output-path isoformDB/database/
        
RuleException:
CalledProcessError in file "/Users/allen/projects/dna_lang/pytorch_borzoi/isoformer/database/pipeline/isoform_db.smk", line 140:
Command 'set -euo pipefail;  
        isoformer-write-records \
            --gene-annotation isoformDB/references/grch38.gencode.v29/cannonical_genes.gff \
            --quantitation isoformDB/intermediates/K562/isoform_quantitation.tsv annot_transcript_id rep2ENCSR983KDL \
            --transcript-annotation isoformDB/intermediates/K562/transcript_annotation.gtf.gz \
            --reference-id grch38.gencode.v29 \
            --dataset-id K562 \
            --output-path isoformDB/database/' returned non-zero exit status 1.
[Fri Aug 22 21:29:24 2025]
Error in rule write_gene_records:
    message: None
    jobid: 1
    input: isoformDB/intermediates/K562/transcript_annotation.gtf.gz, isoformDB/intermediates/K562/isoform_quantitation.tsv, isoformDB/references/grch38.gencode.v29/cannonical_genes.gff
    output: isoformDB/intermediates/K562/db.commited
    shell:
        
        isoformer-write-records \
            --gene-annotation isoformDB/references/grch38.gencode.v29/cannonical_genes.gff \
            --quantitation isoformDB/intermediates/K562/isoform_quantitation.tsv annot_transcript_id rep2ENCSR983KDL \
            --transcript-annotation isoformDB/intermediates/K562/transcript_annotation.gtf.gz \
            --reference-id grch38.gencode.v29 \
            --dataset-id K562 \
            --output-path isoformDB/database/
        
        (command exited with non-zero exit code)
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Fri Aug 22 21:29:24 2025]
Error in rule write_gene_records:
    message: None
    jobid: 1
    input: isoformDB/intermediates/K562/transcript_annotation.gtf.gz, isoformDB/intermediates/K562/isoform_quantitation.tsv, isoformDB/references/grch38.gencode.v29/cannonical_genes.gff
    output: isoformDB/intermediates/K562/db.commited
    shell:
        
        isoformer-write-records \
            --gene-annotation isoformDB/references/grch38.gencode.v29/cannonical_genes.gff \
            --quantitation isoformDB/intermediates/K562/isoform_quantitation.tsv annot_transcript_id rep2ENCSR983KDL \
            --transcript-annotation isoformDB/intermediates/K562/transcript_annotation.gtf.gz \
            --reference-id grch38.gencode.v29 \
            --dataset-id K562 \
            --output-path isoformDB/database/
        
        (command exited with non-zero exit code)
Complete log(s): /Users/allen/projects/dna_lang/pytorch_borzoi/isoformer/database/pipeline/.snakemake/log/2025-08-22T212851.452329.snakemake.log
WorkflowError:
At least one job did not complete successfully.
